WebApplication/Models/ErrorViewModel.cs
using System;

namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication/Models/survay.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    public class survay
    {
        public int Id { get; set; }
        public int PayRateing { get; set; }
        public int SatisfactionRating { get; set; }
        public string feedback { get; set; }

        public survay()
        {

        }

    }
}

WebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication/Controllers/survaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication.Data;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class survaysController : Controller
    {
        private readonly ApplicationDbContext _context;

        public survaysController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: survays
        public async Task<IActionResult> Index()
        {
            return View(await _context.survay.ToListAsync());
        }

        // GET: survays/ShowSearchForm

        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: survays/ShowSearchResults

        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index", await _context.survay.Where(J =>J.feedback.Contains(SearchPhrase) ).ToListAsync());
        }

        // GET: survays/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survay = await _context.survay
                .FirstOrDefaultAsync(m => m.Id == id);
            if (survay == null)
            {
                return NotFound();
            }

            return View(survay);
        }

        // GET: survays/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: survays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PayRateing,SatisfactionRating,feedback")] survay survay)
        {
            if (ModelState.IsValid)
            {
                _context.Add(survay);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(survay);
        }

        // GET: survays/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survay = await _context.survay.FindAsync(id);
            if (survay == null)
            {
                return NotFound();
            }
            return View(survay);
        }

        // POST: survays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PayRateing,SatisfactionRating,feedback")] survay survay)
        {
            if (id != survay.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(survay);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!survayExists(survay.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(survay);
        }

        // GET: survays/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survay = await _context.survay
                .FirstOrDefaultAsync(m => m.Id == id);
            if (survay == null)
            {
                return NotFound();
            }

            return View(survay);
        }

        // POST: survays/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var survay = await _context.survay.FindAsync(id);
            _context.survay.Remove(survay);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool survayExists(int id)
        {
            return _context.survay.Any(e => e.Id == id);
        }
    }
}

WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Web App</h1>
    <p>This is a sample peice demonstrationg a survay based aplication.</a>.</p>
</div>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="survays" asp-action="Index">Survays</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="survays" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication/Views/survays/Create.cshtml
@model WebApplication.Models.survay

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>survay</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PayRateing" class="control-label"></label>
                <input asp-for="PayRateing" class="form-control" />
                <span asp-validation-for="PayRateing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SatisfactionRating" class="control-label"></label>
                <input asp-for="SatisfactionRating" class="form-control" />
                <span asp-validation-for="SatisfactionRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="feedback" class="control-label"></label>
                <input asp-for="feedback" class="form-control" />
                <span asp-validation-for="feedback" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/survays/Delete.cshtml
@model WebApplication.Models.survay

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>survay</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayRateing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayRateing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SatisfactionRating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SatisfactionRating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.feedback)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.feedback)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication/Views/survays/Details.cshtml
@model WebApplication.Models.survay

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>survay</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayRateing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayRateing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SatisfactionRating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SatisfactionRating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.feedback)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.feedback)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication/Views/survays/Edit.cshtml
@model WebApplication.Models.survay

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>survay</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PayRateing" class="control-label"></label>
                <input asp-for="PayRateing" class="form-control" />
                <span asp-validation-for="PayRateing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SatisfactionRating" class="control-label"></label>
                <input asp-for="SatisfactionRating" class="form-control" />
                <span asp-validation-for="SatisfactionRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="feedback" class="control-label"></label>
                <input asp-for="feedback" class="form-control" />
                <span asp-validation-for="feedback" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/survays/Index.cshtml
@model IEnumerable<WebApplication.Models.survay>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PayRateing)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SatisfactionRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.feedback)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PayRateing)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SatisfactionRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.feedback)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication/Views/survays/ShowSearchForm.cshtml
<h4>Search for a survay with the search term in the feedback box</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>